### PR TITLE
AEROGEAR-2233 Custom realm name should be used for original KeyCloak service

### PR DESCRIPTION
**Pull request by vchepeli**
**Describe what this PR does and why we need it**:
[AEROGEAR-2233](https://issues.jboss.org/browse/AEROGEAR-2233)

**Changes proposed in this pull request**
When SHARED_REALM is defined:
- Realm name should be created with SHARED_REALM name

**Which issue this PR fixes (This will close that issue when PR gets merged)**
fixes AEROGEAR-2233

### CODE REVIEW

**Comment by vchepeli** [comment]
ping @maleck13, @philbrookes, @JameelB

**Comment by maleck13** [comment]
Test:
- create no realm
- create with realm
- create shared service with realm

**Comment by maleck13** [comment]
Test worked as expected so I think we just need to get the checks to pass then good to merge

**Comment by JameelB** [comment]
@vchepeli Looks good to me too. You might have to regenerate the dockerfile?

**Comment by JameelB** [comment]
@maleck13 @vchepeli Tested locally.

Verified the following test cases:
- Successfully provisioned a shared keycloak with specified realm
- Successfully provisioned a shared keycloak with no realm specified. (Defaulted to the current namespace)
- Successfully provisioned a linked keycloak service with a specified realm
- Successfully provisioned a linked keycloak service with no realm specified (Defaulted to the current namespace).

**Pull request merged**
