### PR TITLE
AEROGEAR-1992 Add options for shared services

### PR DESCRIPTION
**Pull request by dimitraz**
**Description** 
Update `apb.yml` to include options for shared services. See Phil's proposal [here](https://github.com/aerogear/proposals/blob/master/apbs/use-shared-services-across-namespaces.md).

### CODE REVIEW

**Comment by dimitraz** [comment]
@maleck13 @philbrookes

**Comment by dimitraz** [comment]
@maleck13 yeah I did. Seems to work fine, the CLI picks up the serviceinstance

**Comment by maleck13** [comment]
it a known problem

**Comment by maleck13** [comment]
@wei-lee added realm here as suggested

**Pull request merged**
