### PR TITLE
Remove creation of bearer client on provision

### PR DESCRIPTION
**Pull request by dimitraz**
Config map should now look like this:

image

### CODE REVIEW

**Comment by maleck13** [comment]
@aliok I believe this will solve your issue

**Comment by maleck13** [comment]
@dimitraz I think we can get rid of all the other keys except name, type, uri and public_installation

**Comment by dimitraz** [comment]
ping @maleck13

**Comment by aliok** [comment]
Giving this a try now.

**Comment by aliok** [comment]
Ok, this change is great even though I had to make some adjustments in the Android SDK :) 
Only the necessary infromation is in "public_installation", which is good!

Thanks for the good work!

**Comment by aliok** [comment]
Uhm, one second...

I see this changes the config map. That config map is also used by e.g. a backend app.

@wei-lee  is this ok?

When I check the keycloak.json attached to the mobile security api app, it was like this:
```
{
  "realm": "project2",
  "bearer-only": true,
  "auth-server-url": "https://keycloak-project2.192.168.42.191.nip.io/auth",
  "ssl-required": "external",
  "resource": "api-server",
  "confidential-port": 0,
  "disable-trust-manager" : true
}
```

Now, it is like this (imagine JSON):
```
data:
  name: keycloak
  public_installation: >-
    {"ssl-required": "external", "realm": "project3", "resource":
    "MrBDhcYmuvkjdFFwRLSb", "url":
    "https://keycloak-project3.192.168.42.191.nip.io/auth", "auth-server-url":
    "https://keycloak-project3.192.168.42.191.nip.io/auth"}
  realm: project3
  type: keycloak
  uri: 'https://keycloak-project3.192.168.42.191.nip.io'
```

I was adapting the Android SDK (haven't pushed yet) to the change, but the Keycloak node connector reads this file (thus, the config map) directly.


As I don't know much about the impl details, I was thinking we were already talking about 2 separate things.

**Comment by maleck13** [comment]
There should be no need for any backend app to use the configmap. If a binding is created to keycloak it will create a bearer client and a secret with the info init. This secret can then be consumed in the backend app

**Comment by aliok** [comment]
@maleck13 you're right. we were making this thing work with a config map mount as the binding had some problems. I kind of thought for a moment that's the proper way.

@darahayes any comments? does the binding work already?

**Pull request merged**
