### PR TITLE
fix: don't allow multiple kc instances in one ns

### PR DESCRIPTION
**Pull request by psturc**
### Motivation
https://issues.jboss.org/browse/AEROGEAR-8524

* removed tags from resource names
* decreased ridiculous amount of retries in some tasks
* moved playbooks to `/opt/apb/project` as [message about deprecations suggests](https://github.com/ansibleplaybookbundle/apb-base/blob/master/files/usr/bin/entrypoint.sh#L92)

### CODE REVIEW

**Comment by wei-lee** [comment]
👀

**Comment by wei-lee** [comment]
@psturc any idea why I am getting this error: 
```
'provision' NOT IMPLEMENTED
```

**Comment by psturc** [comment]
@wei-lee I haven't seen this error before.
Try to spin up minishift locally with `psturc` organisation and `AEROGEAR-8524` tag, I just pushed the image there.

**Comment by wei-lee** [comment]
verified on my RHPDS cluster

**Pull request merged**
